# Generated by Django 2.2.16 on 2021-09-08 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
